// order + visibility for each STORY VARIANT (not theme)
export const STORY = {
  neutral: [
    "hero",
    "definition",
    "leber",
    "deutschland",
    "organe",
    "sectionsechs",
    "sectionsieben",
    "sectionacht",
    "sectionneun",
    "sectionzehn",
    "sectionelf",
    "sectionzwoelf",
    "sectiondreizehn",
    "sectionvierzehn",
    "sectionfuenfzehn",
  ],

  positive: [
    "hero",
    "sectionvierzehn",
    "organe",
    "sectionacht",
    "definition",
    "leber",
    "deutschland",
    "sectionneun",
    "sectionzehn",
    "sectionelf",
    "sectionzwoelf",
    "sectiondreizehn",
    "sectionfuenfzehn",
    "sectionsechs",
    "sectionsieben",
  ],

  disturbing: [
    "hero",
    "sectionacht",
    "sectiondreizehn",
    "definition",
    "leber",
    "deutschland",
    "organe",
    "sectionsechs",
    "sectionsieben",
    "sectionneun",
    "sectionzehn",
    "sectionelf",
    "sectionzwoelf",
    "sectionvierzehn",
    "sectionfuenfzehn",
  ],
};